### ISSUE TITLE
Check Team Project 2 Submission 

### ISSUE THREAD

**Issue by ahmad2806** [ahmad2806/Animals-shelter#1]

**Comment by robi-y** [comment]
Nice work.
Please remove redundant text in issue text above.

Also, update the project description via repo. settings (it still say "A template repository with wiki for a team project at JCE's software engineering course")

Some other comments:
- Readme: link to live application is not ready (remove or comment out)
- Inception: somewhat general risks not project related, a use case diagram in not optimal for discussing software structure, better use deployment or even class diagrams

**Comment by ahmad2806** [comment]
we will do as soon as possible .
but we had a question about the time schedule that we set ..

https://github.com/ahmad2806/Animals-shelter/wiki/Inception-Planning

we tried to include every thing we need to do on it and we hope that the
we can stick to Duration time that we sat ,but in Gantt chart we saw that
we have a lot of TF ... do we need to worry about that ?. and maybe
reschedule it again? ,or does it looks good for you (we need an expert
opinion)
thanx for checking this  :)

**Comment by robi-y** [comment]
:+1:
The plan is only an initial one, we will explore this more at week 5
